---
apiVersion: v1
kind: Secret
metadata:
  name: demoapp-1-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/idp-myocp/demoapp-1-gitops